# Generated by Django 2.1.5 on 2019-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='subtitulo')),
                ('caja_izquierda_titulo', models.CharField(max_length=100, verbose_name='caja_izquierda_titulo')),
                ('caja_izquierda_texto', tinymce.models.HTMLField()),
                ('caja_derecha_titulo', models.CharField(max_length=100, verbose_name='caja_derecha_titulo')),
                ('caja_derecha_texto', tinymce.models.HTMLField()),
                ('activo', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internationalization.Idioma')),
            ],
            options={
                'verbose_name': 'Textos Inicio',
            },
        ),
        migrations.CreateModel(
            name='PaletaColores',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('hexadecimal', models.CharField(max_length=100, verbose_name='hexadecimal')),
            ],
        ),
        migrations.CreateModel(
            name='TarifaDescriptorGenerico',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pretitulo', models.CharField(max_length=100, verbose_name='pretitulo')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('caja_1_titulo', models.CharField(max_length=100, verbose_name='caja_1_titulo')),
                ('caja_1_texto', tinymce.models.HTMLField()),
                ('caja_1_icono', models.FileField(upload_to='pagina_tarifas')),
                ('caja_2_titulo', models.CharField(max_length=100, verbose_name='caja_2_titulo')),
                ('caja_2_texto', tinymce.models.HTMLField()),
                ('caja_2_icono', models.FileField(upload_to='pagina_tarifas')),
                ('caja_3_titulo', models.CharField(max_length=100, verbose_name='caja_3_titulo')),
                ('caja_3_texto', tinymce.models.HTMLField()),
                ('caja_3_icono', models.FileField(upload_to='pagina_tarifas')),
                ('caja_4_titulo', models.CharField(max_length=100, verbose_name='caja_4_titulo')),
                ('caja_4_texto', tinymce.models.HTMLField()),
                ('caja_4_icono', models.FileField(upload_to='pagina_tarifas')),
                ('activo', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internationalization.Idioma')),
            ],
            options={
                'verbose_name': 'Textos cajitas tarifa',
            },
        ),
        migrations.CreateModel(
            name='TxtContacto',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('provincia', models.CharField(max_length=100, verbose_name='provincia')),
                ('codigo_postal', models.CharField(max_length=100, verbose_name='codigo_postal')),
                ('calle', models.CharField(max_length=100, verbose_name='calle')),
                ('activo', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internationalization.Idioma')),
            ],
        ),
    ]
