# Generated by Django 2.1.5 on 2019-01-18 10:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RangoICC',
            fields=[
                ('rango_icc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rango_icc_init', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999999999), django.core.validators.MinValueValidator(0)], verbose_name='Rango Inicial')),
                ('rango_icc_end', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999999999), django.core.validators.MinValueValidator(0)], verbose_name='Rango Final')),
                ('rango_icc_activo', models.BooleanField(default=False, verbose_name='Rango Activo')),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Rango ICC',
                'verbose_name_plural': 'Rangos ICC',
            },
        ),
    ]
