# Generated by Django 2.1.5 on 2019-01-18 10:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('codcausa', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Codigo causa')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', tinymce.models.HTMLField()),
                ('thumbnail_url', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Thumbnail Url')),
                ('fechainicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('visible', models.IntegerField(blank=True, choices=[(0, 'False'), (1, 'True')], null=True, verbose_name='visible')),
                ('recaudacion', models.FloatField(blank=True, default=0, verbose_name='Recaudación')),
                ('activo', models.BooleanField(default=0, verbose_name='Causa Actual')),
                ('valido_altrebit', models.BooleanField(default=0, verbose_name='Causa Actual')),
            ],
        ),
    ]
