# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='codcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumo_Cliente', to='cliente.Cliente', verbose_name='Codigo Cliente'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='codcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='coddir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_direccion', to='cliente.DirClientes'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='codpago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.FormasPago'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='codpais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Pais'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='idpedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.PedidoCli'),
        ),
        migrations.AlterField(
            model_name='facturascli',
            name='idprovincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Provincia'),
        ),
        migrations.AlterField(
            model_name='lineapedidocli',
            name='codimpuesto',
            field=models.ForeignKey(default='IVA18%', on_delete=django.db.models.deletion.CASCADE, related_name='LineaPedidoCli_Impuesto', to='facturacion.Impuesto', verbose_name='codimpuesto'),
        ),
        migrations.AlterField(
            model_name='lineapedidocli',
            name='idpedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LineaPedidoCli_PedidoCli', to='facturacion.PedidoCli', verbose_name='idpedido'),
        ),
        migrations.AlterField(
            model_name='lineapedidocli',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LineaPedidoCli_Articulo', to='catalogo.Articulo', verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='lineasfacturascli',
            name='idfactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturasCli'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='codcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoCli_Cliente', to='cliente.Cliente', verbose_name='Codigo Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='coddir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoCli_DirClientes', to='cliente.DirClientes', verbose_name='Codigo Dirección'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='coddirEnvio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoCli_DirClientesEnvio', to='cliente.DirClientes', verbose_name='Codigo Dirección Envío'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='codpago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.FormasPago', verbose_name='Formas de Pago - TPV'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='formaEnvio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoCli_FormasEnvio', to='facturacion.FormasEnvio', verbose_name='Forma de envío'),
        ),
        migrations.AlterField(
            model_name='pedidocli',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PedidoCli_FormasPago', to='facturacion.FormasPago', verbose_name='Forma de pago'),
        ),
    ]
