# Generated by Django 2.1.5 on 2019-02-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20190207_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineasfacturascli',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Articulo'),
        ),
    ]
