# -*- coding: utf-8 -*-


from django.db import models, migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
        ('omv', '0001_initial'),
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('referencia', models.CharField(max_length=100, serialize=False, editable=False, primary_key=True)),
                ('slug', models.SlugField(editable=False)),
                ('descripcion', models.CharField(max_length=250, verbose_name=b'Descripci\xc3\xb3n [ES]')),
                ('descripcion_va', models.CharField(max_length=250, verbose_name=b'Descripci\xc3\xb3n [VA]', blank=True)),
                ('pvp', models.FloatField(default=0)),
                ('stockfis', models.FloatField(default=0)),
                ('descripcion_breve', models.CharField(max_length=250, verbose_name=b'Descripci\xc3\xb3n breve [ES]')),
                ('descripcion_breve_va', models.CharField(max_length=250, verbose_name=b'Descripci\xc3\xb3n breve [VA]', blank=True)),
                ('descripcion_larga', tinymce.models.HTMLField(verbose_name=b'Especificaciones [ES]')),
                ('descripcion_larga_va', tinymce.models.HTMLField(verbose_name=b'Especificaciones [VA]', blank=True)),
                ('template', models.IntegerField(verbose_name=b'Template Seleccionado', choices=[(1, b'Template 1'), (2, b'Template 2'), (3, b'Template 3')])),
                ('imagen', models.FileField(upload_to=b'pagina_tarifas', verbose_name=b'Imagen')),
                ('thumbnail', models.FileField(upload_to=b'pagina_tarifas', verbose_name=b'thumbnail')),
                ('activo', models.BooleanField(default=0, verbose_name=b'Art\xc3\xadculo Activo')),
                ('visible', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('secompra', models.BooleanField(default=True)),
                ('stockmax', models.FloatField(default=0)),
                ('codimpuesto', models.CharField(default=b'IVA21%', max_length=b'10', null=True)),
                ('observaciones', models.TextField(null=True, blank=True)),
                ('codbarras', models.CharField(max_length=18, null=True, verbose_name=b'Codigo Barras', blank=True)),
                ('nostock', models.BooleanField(default=False)),
                ('controlstock', models.BooleanField(default=False)),
                ('tipocodbarras', models.CharField(blank=True, max_length=8, null=True, choices=[(b'Code39', b'Code39'), (b'Code128', b'Code128'), (b'Code128B', b'Code128B'), (b'Code128C', b'Code128C'), (b'Code128R', b'Code128R'), (b'EAN', b'EAN'), (b'ISBN', b'ISBN'), (b'UPC', b'UPC'), (b'CodeI25', b'CodeI25'), (b'CBR', b'CBR'), (b'MSI', b'MSI'), (b'PLS', b'PLS'), (b'Code93', b'Code93')])),
                ('sevende', models.BooleanField(default=True)),
                ('venta_online', models.BooleanField(default=True)),
                ('stockmin', models.FloatField(default=0)),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('num_camara', models.FloatField()),
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('codfamilia', models.CharField(max_length=4, serialize=False, verbose_name='C\xf3digo Familia', primary_key=True)),
                ('slug', models.SlugField(editable=False)),
                ('nombre', models.CharField(max_length=200, verbose_name=b'Nombre [ES]')),
                ('nombre_va', models.CharField(max_length=200, verbose_name=b'Nombre [VA]', blank=True)),
                ('icono', models.FileField(upload_to=b'familia')),
                ('pretitulo', models.CharField(max_length=200, verbose_name=b'Pretitulo [ES]')),
                ('pretitulo_va', models.CharField(max_length=200, verbose_name=b'Pretitulo [VA]', blank=True)),
                ('titulo', models.CharField(max_length=200, verbose_name=b'Titulo [ES]')),
                ('titulo_va', models.CharField(max_length=200, verbose_name=b'Titulo [VA]', blank=True)),
                ('precio_cabecera', models.FloatField(null=True)),
                ('imagen_cabecera', models.FileField(null=True, upload_to=b'familia')),
                ('thumbnail', models.FileField(upload_to=b'familia', null=True, editable=False)),
                ('activo', models.BooleanField(default=False)),
                ('texto_cabecera', tinymce.models.HTMLField(verbose_name=b'Texto cabecera [ES]')),
                ('texto_cabecera_va', tinymce.models.HTMLField(verbose_name=b'Texto cabecera [VA]', blank=True)),
                ('subtexto_cabecera', tinymce.models.HTMLField(verbose_name=b'Subtexto cabecera [ES]')),
                ('subtexto_cabecera_va', tinymce.models.HTMLField(verbose_name=b'Subtexto cabecera [VA]', blank=True)),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('color', models.ForeignKey(related_name='Familia_PaletaColores', to='pagina.PaletaColores', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('Marca', models.CharField(max_length=100)),
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('num_pantalla', models.FloatField()),
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('num_procesador', models.CharField(max_length=100)),
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('num_ram', models.CharField(max_length=100)),
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtarifa',
            fields=[
                ('subtarifa_id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('subtarifa_datos_internet', models.FloatField(null=True, verbose_name=b'Importe Datos', blank=True)),
                ('subtarifa_cent_minuto', models.FloatField(null=True, verbose_name=b'Importe minutos (cent/min)', blank=True)),
                ('subtarifa_est_llamada', models.FloatField(null=True, blank=True)),
                ('subtarifa_precio_sms', models.FloatField(null=True, verbose_name=b'Importe sms', blank=True)),
                ('subtarifa_velocidad_conexion_subida', models.FloatField(null=True, verbose_name=b'Velocidad de conexi\xc3\xb3n subida', blank=True)),
                ('subtarifa_velocidad_conexion_bajada', models.FloatField(null=True, verbose_name=b'Velocidad de conexi\xc3\xb3n bajada', blank=True)),
                ('subtarifa_num_canales', models.IntegerField(null=True, blank=True)),
                ('subtarifa_minutos_gratis', models.IntegerField(null=True, verbose_name=b'Minutos gratis', blank=True)),
                ('subtarifa_siglas_omv', models.CharField(max_length=100, null=True, verbose_name=b'Siglas de la tarifa', blank=True)),
                ('tipo_tarifa', models.IntegerField(default=0, choices=[(1, b'M\xc3\xb3vil'), (2, b'Fijo'), (3, b'Fibra'), (4, b'Wifi'), (5, b'TV')])),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('subtarifa_omv', models.ForeignKey(verbose_name=b'Omv asociado a Tarifa', blank=True, to='omv.Omv', null=True)),
            ],
            options={
                'verbose_name': 'Paquete Tarifa',
                'verbose_name_plural': 'Paquetes Tarifa',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('codtarifa', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('nombretarifa', models.CharField(max_length=100, verbose_name=b'Nombre tarifa')),
                ('slug', models.SlugField(editable=False)),
                ('pretitulo', models.CharField(max_length=100, verbose_name=b'Pretitulo [ES]')),
                ('pretitulo_va', models.CharField(max_length=100, verbose_name=b'Pretitulo [VA]', blank=True)),
                ('logo', models.FileField(upload_to=b'Logo')),
                ('precio', models.FloatField(verbose_name=b'Importe tarifa ')),
                ('activo', models.BooleanField(default=0, verbose_name=b'Activo')),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('color', models.ForeignKey(related_name='Tarifa_PaletaColores', to='pagina.PaletaColores', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template1',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('pretitulo', models.CharField(max_length=100, verbose_name=b'pretitulo')),
                ('caja_1_titulo', models.CharField(max_length=100, verbose_name=b'caja_1_titulo')),
                ('caja_1_texto', tinymce.models.HTMLField()),
                ('caja_2_titulo', models.CharField(max_length=100, verbose_name=b'caja_2_titulo')),
                ('caja_2_texto', tinymce.models.HTMLField()),
                ('caja_3_titulo', models.CharField(max_length=100, verbose_name=b'caja_3_titulo')),
                ('caja_3_texto', tinymce.models.HTMLField()),
                ('caja_4_titulo', models.CharField(max_length=100, verbose_name=b'caja_4_titulo')),
                ('caja_4_texto', tinymce.models.HTMLField()),
                ('imagen1', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen1')),
                ('imagen2', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen2')),
                ('imagen3', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen3')),
                ('imagen_fondo_cabecera', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cabecera')),
                ('imagen_fondo_cuerpo', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cuerpo')),
                ('articulo', models.OneToOneField(related_name='template1_articulo', to='catalogo.Articulo')),
                ('idioma', models.ForeignKey(to='internationalization.Idioma', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template2',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('pretitulo', models.CharField(max_length=100, verbose_name=b'pretitulo')),
                ('caja_1_titulo', models.CharField(max_length=100, verbose_name=b'caja_1_titulo')),
                ('caja_1_texto', tinymce.models.HTMLField()),
                ('caja_2_titulo', models.CharField(max_length=100, verbose_name=b'caja_2_titulo')),
                ('caja_2_texto', tinymce.models.HTMLField()),
                ('caja_3_titulo', models.CharField(max_length=100, verbose_name=b'caja_3_titulo')),
                ('caja_3_texto', tinymce.models.HTMLField()),
                ('caja_4_titulo', models.CharField(max_length=100, verbose_name=b'caja_4_titulo')),
                ('caja_4_texto', tinymce.models.HTMLField()),
                ('imagen1', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen1')),
                ('imagen2', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen2')),
                ('imagen3', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen3')),
                ('imagen4', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen4')),
                ('imagen_fondo_cabecera', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cabecera')),
                ('imagen_fondo_cuerpo', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cuerpo')),
                ('articulo', models.OneToOneField(related_name='template2_articulo', to='catalogo.Articulo')),
                ('idioma', models.ForeignKey(to='internationalization.Idioma', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template3',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('pretitulo', models.CharField(max_length=100, verbose_name=b'pretitulo')),
                ('franja_1_texto', tinymce.models.HTMLField()),
                ('franja_1_fondo', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cabecera')),
                ('caja_1_titulo', models.CharField(max_length=100, verbose_name=b'caja_1_titulo')),
                ('caja_1_texto', tinymce.models.HTMLField()),
                ('caja_2_titulo', models.CharField(max_length=100, verbose_name=b'caja_2_titulo')),
                ('caja_2_texto', tinymce.models.HTMLField()),
                ('franja_2_texto', tinymce.models.HTMLField()),
                ('franja_2_fondo', models.FileField(upload_to=b'Templates', verbose_name=b'imagen_fondo_cabecera')),
                ('imagen1', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen1')),
                ('imagen2', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen2')),
                ('imagen3', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen3')),
                ('imagen4', models.FileField(upload_to=b'Templates', verbose_name=b'Imagen4')),
                ('articulo', models.OneToOneField(related_name='template3_articulo', to='catalogo.Articulo')),
                ('idioma', models.ForeignKey(to='internationalization.Idioma', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtarifa',
            name='subtarifa_tarifa',
            field=models.ForeignKey(related_name='subtarifa_tarifa', verbose_name=b'Tarifa', to='catalogo.Tarifa'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='camara',
            field=models.ForeignKey(related_name='Articulo_Camara', blank=True, to='catalogo.Camara', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='codfamilia',
            field=models.ForeignKey(related_name='familia_codfamilia', to='catalogo.Familia'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(related_name='Articulo_Marca', to='catalogo.Marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='pantalla',
            field=models.ForeignKey(related_name='Articulo_Pantalla', blank=True, to='catalogo.Pantalla', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='procesador',
            field=models.ForeignKey(related_name='Articulo_Procesador', blank=True, to='catalogo.Procesador', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ram',
            field=models.ForeignKey(related_name='Articulo_Ram', blank=True, to='catalogo.Ram', null=True),
        ),
        migrations.AlterIndexTogether(
            name='familia',
            index_together=set([('codfamilia', 'nombre')]),
        ),
    ]
