# Generated by Django 2.1.5 on 2019-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internationalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmail',
            fields=[
                ('datos_email_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_receiver', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Receptor')),
                ('email_sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Envio')),
                ('email_sender_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password Email Envio')),
                ('server', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servidor')),
                ('port', models.IntegerField(blank=True, default=25, null=True, verbose_name='Puerto Servidor')),
                ('datos_email_default', models.BooleanField(default=False, verbose_name='Datos Email por Defecto')),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Datos Email',
                'verbose_name_plural': 'Datos Email',
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('datos_empresa_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Empresa')),
                ('cifnif', models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Logo Url')),
                ('icon_logo', models.FileField(blank=True, null=True, upload_to='icon_logo', verbose_name='Icono Logo Url')),
                ('mapa_cobertura', models.FileField(blank=True, null=True, upload_to='mapa_cobertura', verbose_name='Mapa Cobertura Url')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=300, null=True, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pais')),
                ('zipcode', models.CharField(blank=True, max_length=300, null=True, verbose_name='Cod.Postal')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('location_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('datos_empresa_default', models.BooleanField(default=False, verbose_name='Empresa por Defecto')),
                ('social_twitter', models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter')),
                ('social_facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Datos Empresa',
                'verbose_name_plural': 'Datos Empresa',
            },
        ),
        migrations.CreateModel(
            name='InfoEmpresa',
            fields=[
                ('info_empresa_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='info_empresa_image', verbose_name='Info Empresa Imagen')),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('datos_empresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_empresa_fk', to='datos_empresa.DatosEmpresa', verbose_name='Datos Empresa')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internationalization.Idioma')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Info Empresa',
                'verbose_name_plural': 'Info Empresas',
            },
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('texto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internationalization.Idioma')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Texto Contrato',
                'verbose_name_plural': 'Texto Contratos',
            },
        ),
        migrations.CreateModel(
            name='TextosContrato',
            fields=[
                ('textos_contrato_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textos_contrato_default', models.BooleanField(default=False, verbose_name='Textos Contrato por Defecto')),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Textos Contrato',
                'verbose_name_plural': 'Textos Contratos',
            },
        ),
        migrations.AddField(
            model_name='texto',
            name='textos_contrato_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textos_contrato_fk', to='datos_empresa.TextosContrato', verbose_name='Textos Contrato'),
        ),
        migrations.AddField(
            model_name='datosemail',
            name='datos_empresa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_empresa.DatosEmpresa', verbose_name='Datos Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='texto',
            unique_together={('textos_contrato_fk', 'key', 'idioma')},
        ),
        migrations.AlterUniqueTogether(
            name='infoempresa',
            unique_together={('datos_empresa_fk', 'key', 'idioma')},
        ),
    ]
