# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosemail',
            name='datos_empresa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_empresa.DatosEmpresa', verbose_name='Datos Empresa'),
        ),
        migrations.AlterField(
            model_name='infoempresa',
            name='datos_empresa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_empresa_fk', to='datos_empresa.DatosEmpresa', verbose_name='Datos Empresa'),
        ),
        migrations.AlterField(
            model_name='infoempresa',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internationalization.Idioma'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internationalization.Idioma'),
        ),
        migrations.AlterField(
            model_name='texto',
            name='textos_contrato_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos_contrato_fk', to='datos_empresa.TextosContrato', verbose_name='Textos Contrato'),
        ),
    ]
