# Generated by Django 2.1.5 on 2019-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_empresa', '0002_auto_20190207_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosemail',
            name='emailname_receiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Envio nombre'),
        ),
        migrations.AlterField(
            model_name='datosemail',
            name='email_receiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Envio'),
        ),
        migrations.AlterField(
            model_name='datosemail',
            name='email_sender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario SMTP'),
        ),
        migrations.AlterField(
            model_name='datosemail',
            name='email_sender_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password SMTP'),
        ),
    ]
