# Generated by Django 2.1.5 on 2019-02-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_empresa', '0003_auto_20190213_2033'),
        ('datos_empresa', '0003_auto_20190214_1557'),
    ]

    operations = [
    ]
