# Generated by Django 2.1.5 on 2019-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('codcomunidad', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codpais', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codiso', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=2, null=True)),
                ('codcomunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Comunidad')),
                ('codpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.Pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='codpais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.Pais'),
        ),
    ]
