# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='codpais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Pais'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codcomunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Comunidad'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codpais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Pais'),
        ),
    ]
