# Generated by Django 2.1.5 on 2019-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallApi',
            fields=[
                ('call_id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120, verbose_name='url')),
                ('authfield', models.CharField(max_length=120, verbose_name='authfield info')),
                ('trans_call', models.IntegerField(blank=True, choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT')], null=True, verbose_name='Tipo de Transacción')),
            ],
        ),
        migrations.CreateModel(
            name='Omv',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('codigo', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('activo', models.BooleanField(default=0, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='ParamCallApi',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=120, verbose_name='param nombre')),
                ('requerido', models.BooleanField(default=None, verbose_name='Requerido')),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CallApi_ParamCallApi', to='omv.CallApi', verbose_name='Call OMV')),
            ],
        ),
        migrations.CreateModel(
            name='ParamCallBackApi',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=120, verbose_name='param nombre')),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CallApi_ParamCallBackApi', to='omv.CallApi', verbose_name='Call OMV')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCallApi',
            fields=[
                ('tid', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='UserApiOmv',
            fields=[
                ('uid', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('user_login', models.CharField(max_length=30, verbose_name='User Login')),
                ('user_password', models.CharField(max_length=30, verbose_name='User Password')),
                ('codigo_omv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserOmv_Omv', to='omv.Omv', verbose_name='Codigo OMV')),
            ],
        ),
        migrations.AddField(
            model_name='callapi',
            name='codigo_omv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserOmv_CallApi', to='omv.Omv', verbose_name='Codigo OMV'),
        ),
        migrations.AddField(
            model_name='callapi',
            name='typecall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TypeCallApi_CallApi', to='omv.TypeCallApi', verbose_name='Tipo de Call'),
        ),
    ]
