# Generated by Django 2.1.5 on 2019-01-31 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
