# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190131_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codcuentadom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.CuentasbcoCli', verbose_name='Cuenta Domiciliacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='consumer_user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_Codcliente', to=settings.AUTH_USER_MODEL, verbose_name='Consumer User'),
        ),
        migrations.AlterField(
            model_name='cuentasbcocli',
            name='codcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentasbco_cliente', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='dirclientes',
            name='codcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DirClientes_Cliente', to='cliente.Cliente', verbose_name='Codigo Cliente'),
        ),
        migrations.AlterField(
            model_name='dirclientes',
            name='idprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dir_prov', to='geo.Provincia', verbose_name='Id Provincia'),
        ),
        migrations.AlterField(
            model_name='gruposcliente',
            name='codtarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GruposClientes_Tarifa', to='catalogo.Tarifa', verbose_name='Codigo tarifa'),
        ),
        migrations.AlterField(
            model_name='mobilsclients',
            name='codcuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MobilsClients_CuentasbcoCli', to='cliente.CuentasbcoCli', verbose_name='Cuenta Cliente'),
        ),
        migrations.AlterField(
            model_name='mobilsclients',
            name='coddir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MobilsClients_DirClientes', to='cliente.DirClientes', verbose_name='Datos de Facturación'),
        ),
        migrations.AlterField(
            model_name='mobilsclients',
            name='codtarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MobilsClients_Tarifa', to='catalogo.Tarifa', verbose_name='Codigo Tarifa'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.CuentasbcoCli'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.DirClientes', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Tarifa', verbose_name='Tarifa'),
        ),
    ]
